# Dataset Root Directory
# 주의: 절대 경로를 권장하며, 상대 경로 사용 시 실행 위치에 유의하세요.
path: ../datasets/coco128  # 데이터셋 루트 디렉토리

train: images/train2017  # 학습 이미지 (relative to 'path')
val: images/train2017    # 검증 이미지 (relative to 'path')
test:  # 테스트 이미지 (Optional)

# Classes Configuration
nc: 80  # number of classes
names:  # 0-based indexing
  0: person
  1: bicycle
  2: car